language : minimal

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
- docker -v && docker-compose -v
- sudo rm /usr/local/bin/docker-compose
- curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


install:
- docker-compose -v
- docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
